/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.DepartamentoDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.CotiDepa;

/**
 *
 * @author Matio_000
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnqCotizacion = new javax.swing.JMenu();
        mnuIngresar = new javax.swing.JMenuItem();
        mnqVer = new javax.swing.JMenu();
        mnuCotizaciones = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnqCotizacion.setText("Cotizacion");

        mnuIngresar.setText("Ingresar Cotizacion");
        mnuIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngresarActionPerformed(evt);
            }
        });
        mnqCotizacion.add(mnuIngresar);

        jMenuBar1.add(mnqCotizacion);

        mnqVer.setText("Ver");

        mnuCotizaciones.setText("Cotizaciones Realizadas");
        mnuCotizaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCotizacionesActionPerformed(evt);
            }
        });
        mnqVer.add(mnuCotizaciones);

        jMenuBar1.add(mnqVer);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngresarActionPerformed
        VentanaIngreso ven=new VentanaIngreso();
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
        ven.setTitle("Ingreso Cotizacion");
        ven.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }//GEN-LAST:event_mnuIngresarActionPerformed

    private void mnuCotizacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCotizacionesActionPerformed
        VentanaMostrar ven=new VentanaMostrar();
        ven.setVisible(true);
        ven.setLocationRelativeTo(null);
        ven.setTitle("Cotizaciones");
        ven.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE); 
    }//GEN-LAST:event_mnuCotizacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnqCotizacion;
    private javax.swing.JMenu mnqVer;
    private javax.swing.JMenuItem mnuCotizaciones;
    private javax.swing.JMenuItem mnuIngresar;
    // End of variables declaration//GEN-END:variables
}
